# Generated by Django 3.2.13 on 2022-04-28 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_name', models.CharField(max_length=50)),
                ('continent_slug', models.SlugField()),
                ('continent_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('country_slug', models.SlugField()),
                ('country_code', models.CharField(max_length=10)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItineraryAppManagement.continent')),
            ],
        ),
        migrations.CreateModel(
            name='Customized_Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('night', models.CharField(max_length=100)),
                ('no_of_adults', models.IntegerField()),
                ('no_of_childs', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('vacation', models.CharField(max_length=100)),
                ('info', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Itineraries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('price', models.IntegerField()),
                ('package', models.CharField(default='5 Days|2 Night', max_length=50)),
                ('currency_code', models.CharField(max_length=5)),
                ('small_description', models.TextField(max_length=175)),
                ('long_description', models.TextField()),
                ('best_itinerary', models.BooleanField()),
                ('top_rated_itinerary', models.BooleanField()),
                ('image', models.ImageField(upload_to='Itineraries')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItineraryAppManagement.continent')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItineraryAppManagement.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItineraryAppManagement.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItineraryAppManagement.country'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ItineraryAppManagement.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItineraryAppManagement.itineraries')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.account')),
            ],
        ),
    ]
