# Generated by Django 3.2.13 on 2022-05-02 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ItineraryAppManagement', '0002_auto_20220430_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerariesimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Itineraries')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItineraryAppManagement.itineraries')),
            ],
        ),
    ]
