# Generated by Django 3.2.13 on 2022-05-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItineraryAppManagement', '0005_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customized_itinerary',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
