# Generated by Django 3.2.13 on 2022-05-13 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_account_country_account_mobile_account_nationality'),
        ('ItineraryAppManagement', '0006_customized_itinerary_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customized_itinerary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.account'),
        ),
    ]
