# Generated by Django 3.2.13 on 2022-05-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItineraryAppManagement', '0007_customized_itinerary_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customized_itinerary',
            name='last_login',
        ),
        migrations.AddField(
            model_name='customized_itinerary',
            name='message',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
