# Generated by Django 3.2.9 on 2022-05-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItineraryAppManagement', '0008_auto_20220513_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraries',
            name='top_rated_itinerary',
            field=models.CharField(choices=[('0', '0'), ('0.5', '0.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5')], default='0', max_length=10),
        ),
    ]
