# Generated by Django 3.2.9 on 2022-05-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItineraryAppManagement', '0011_auto_20220523_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itineraries',
            old_name='top_rated_itinerary',
            new_name='rating',
        ),
    ]
