# Generated by Django 3.2.9 on 2022-05-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItineraryAppManagement', '0013_auto_20220528_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customized_itinerary',
            name='message',
        ),
        migrations.RemoveField(
            model_name='customized_itinerary',
            name='user',
        ),
    ]
