# Generated by Django 3.2.9 on 2022-05-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItineraryAppManagement', '0014_auto_20220529_1320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itineraries',
            new_name='Itinerarie',
        ),
    ]
