# Generated by Django 3.2.9 on 2022-06-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItineraryAppManagement', '0017_alter_itinerarie_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customized_itinerary',
            name='continent',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customized_itinerary',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customized_itinerary',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
