# Generated by Django 3.2.9 on 2022-06-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItineraryAppManagement', '0018_auto_20220606_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
