# Generated by Django 4.0.5 on 2022-06-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItineraryAppManagement', '0020_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='countryphone_code',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
