# Generated by Django 3.2.13 on 2022-05-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_account_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
